build:
  environment:
    php:
      version: '7.3'
  dependencies:
    before:
      - composer self-update
      - wget -O phpunit.phar https://phar.phpunit.de/phpunit-7.5.9.phar
  tests:
    override:
      - command: ./phpunit.phar --coverage-clover=clover.xml
        coverage:
          file:  clover.xml
          format: php-clover
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      ternary_operator:
        in_short_version: false
      other:
        after_type_cast: true
